### ISSUE TITLE
Integrating  collaborative whiteboard and breakout rooms 

### ISSUE THREAD

**Issue by cdeshapriya** [nkonev/videochat#4]
I'm  happy sponsor these two features under same open source license of your projects.  Thank you very much creating such an amazing integration for us

**Comment by nkonev** [comment]
Thank you for your offer, but right now I have no capacity to make any obligations about features you desired.

By the way, my intent is to start work on plugin api, which as a result will allow to expand this project by new functionality.

**Comment by cdeshapriya** [comment]
That's great news
