### ISSUE TITLE
help setting up in k8s

### ISSUE THREAD

**Issue by kmamtora** [nkonev/videochat#7]
hi @nkonev , 

hope you are doing well. I need to setup LiveKit in k8s I am unable to do in docker compose also can you help me for the same

**Comment by nkonev** [comment]
Hi! Thank you. Unfortunately, right now I don't have time and resources to make a k8s deployment. But in some time I plan to invest the time there. Right now only Ansible installation is available. For the deployment LiveKit in k8s it's better to consult with their(I'm not a member of Livekit team) helm chart https://github.com/livekit/livekit-helm.
