### ISSUE TITLE
How to run the code?

### ISSUE THREAD

**Issue by Sotatek-ChienDao23** [nkonev/videochat#8]
Can you give me an instruction to run the code?

**Comment by nkonev** [comment]
**Environment**: 
`docker compose up -d`

**Services**
Without IDE: In general you can look at makefiles in the each services, they have `run-demo` target.

- https://github.com/nkonev/videochat/blob/master/aaa/Makefile
- https://github.com/nkonev/videochat/blob/master/chat/Makefile
- https://github.com/nkonev/videochat/blob/master/event/Makefile
- https://github.com/nkonev/videochat/blob/master/frontend/Makefile
- https://github.com/nkonev/videochat/blob/master/notification/Makefile
- https://github.com/nkonev/videochat/blob/master/public/Makefile
- https://github.com/nkonev/videochat/blob/master/storage/Makefile
- https://github.com/nkonev/videochat/blob/master/video/Makefile

With IDE: just run main.go / AaaApplication.java
For development purposes you can run `npm run dev` in `frontend` and `public`.
