### ISSUE TITLE
Bad Gateway when run behind Caddy Server

### ISSUE THREAD

**Issue by sanyaade-teachings** [nkonev/videochat#9]
Hi Everyone,

I installed it using the docker-compose with Caddy Server as a proxy
reverse_proxy localhost:8081

the above gave a bad gateway. See below
![image](https://github.com/user-attachments/assets/1ad5f6f3-6176-4263-92f6-9ee222da4838)

Any help or pointer will be well appreciated

God blesses!!!

Regards

**Comment by nkonev** [comment]
Hi!
This project is designed to work only with Traefik;

For the installation on a server there is Ansible playbook https://github.com/nkonev/videochat/tree/master/install/ansible.
For the local development just follow https://github.com/nkonev/videochat/blob/master/development.md#start-the-development.

I've never tested it with Caddy, so I can't help here.

**Comment by sanyaade-teachings** [comment]
> Hi! This project is designed to work only with Traefik;
> 
> For the installation on a server there is Ansible playbook https://github.com/nkonev/videochat/tree/master/install/ansible. For the local development just follow https://github.com/nkonev/videochat/blob/master/development.md#start-the-development.
> 
> I've never tested it with Caddy, so I can't help here.

Okay, I will follow those and do a customised local edition. I think I can disable/remove Traefik
Also reviewing similar packages
Opportunity to learn Ansible on Debian/Ubuntu

God blesses!!!

Regards
